In [2]:
import numpy as np
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

In [9]:
np.dot(A, B)

array([[ 4,  5,  6,  7],
       [12, 17, 22, 27],
       [20, 29, 38, 47]])

In [10]:
print(C)

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


In [12]:
D = C.max()
print(D)

47
